@startuml
'https://plantuml.com/use-case-diagram

actor "System Administrator" as Admin


usecase "US01 - Buy vehicles" as US01
usecase "US02 - List vehicles" as US02
usecase "US03 - List sellers" as US03
usecase "US04 - Add seller" as US04
usecase "US05 - Update seller" as US05
usecase "US06 - Change Vehicles status" as US06
usecase "US07 - Create Vehicle" as US07


Admin -down -> US01
Admin -down -> US02
Admin -down -> US03
Admin -down -> US04
Admin -down -> US05
Admin -down -> US06
Admin -down -> US07

@enduml